name: meu_projeto
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_blue_plus: 1.31.0
  flutter_tts: 4.2.5

dev_dependencies:
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/splash.png

# ==================== FLUTTER NATIVE SPLASH CONFIG ====================
flutter_native_splash:
  color: "#FFFFFF"   # this is the background color
  image: assets/images/logo/splash.png
  android: true
  ios: true
  fullscreen: true

  android_12:
    image: assets/images/logo/splash.png
    icon_background_color: "#FFFFFF"